-- 会员新开 / 续费流水与月度统计。
-- 旧资料只能可靠回填首次开通；此迁移之后的每次会员变更都会精确记录。

CREATE TABLE IF NOT EXISTS public.vip_membership_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('new', 'renew')),
  days integer NOT NULL CHECK (days > 0),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  expire_before timestamptz,
  expire_after timestamptz NOT NULL,
  source text NOT NULL DEFAULT 'admin',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS exclude_from_stats boolean NOT NULL DEFAULT false;
UPDATE public.profiles
   SET exclude_from_stats = true
 WHERE coalesce(is_demo_account, false)
    OR lower(email) = '915877953@qq.com';

CREATE INDEX IF NOT EXISTS vip_membership_events_occurred_at_idx
  ON public.vip_membership_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS vip_membership_events_email_idx
  ON public.vip_membership_events (lower(user_email), occurred_at DESC);

ALTER TABLE public.vip_membership_events
  DROP CONSTRAINT IF EXISTS vip_membership_events_event_type_check;
ALTER TABLE public.vip_membership_events
  ADD CONSTRAINT vip_membership_events_event_type_check
  CHECK (event_type IN ('new', 'renew'));

-- 仅回填 2026-08 起可确认的首次开通记录，不把未知的历史续费臆测为新开。
INSERT INTO public.vip_membership_events
  (user_email, event_type, days, occurred_at, expire_before, expire_after, source)
SELECT p.email, 'new', 30, p.vip_started_at, NULL, p.vip_expire, 'historical_backfill'
FROM public.profiles p
WHERE p.vip_started_at >= timestamptz '2026-08-01 00:00:00+08'
  AND p.vip_expire IS NOT NULL
  AND NOT coalesce(p.is_demo_account, false)
  AND NOT EXISTS (
    SELECT 1 FROM public.vip_membership_events e
    WHERE e.source = 'historical_backfill'
      AND lower(e.user_email) = lower(p.email)
  );

-- 根据持续会员总时长补推历史续费：现行周期为 31 天，早期的 30 天周期也会
-- 落入同一续费次数。例如总时长 61 天 = 新开 1 次 + 续费 1 次。
WITH membership_duration AS (
  SELECT p.email, p.vip_started_at, p.vip_expire,
         greatest(0, ceil(extract(epoch FROM (p.vip_expire - p.vip_started_at)) / 86400.0 / 31.0)::integer - 1) AS renew_count
  FROM public.profiles p
  WHERE p.vip_started_at >= timestamptz '2026-08-01 00:00:00+08'
    AND p.vip_expire IS NOT NULL
    AND NOT coalesce(p.is_demo_account, false)
), inferred AS (
  SELECT d.email,
         d.vip_expire - ((d.renew_count - g.n + 1) * interval '31 days') AS occurred_at
  FROM membership_duration d
  CROSS JOIN LATERAL generate_series(1, d.renew_count) AS g(n)
)
INSERT INTO public.vip_membership_events
  (user_email, event_type, days, occurred_at, expire_before, expire_after, source)
SELECT i.email, 'renew', 31, i.occurred_at, i.occurred_at, i.occurred_at + interval '31 days', 'historical_inferred'
FROM inferred i
WHERE NOT EXISTS (
  SELECT 1 FROM public.vip_membership_events e
  WHERE e.source = 'historical_inferred'
    AND lower(e.user_email) = lower(i.email)
    AND e.occurred_at = i.occurred_at
);

CREATE OR REPLACE FUNCTION public._blys_log_vip_membership_event(
  p_email text,
  p_expire_before timestamptz,
  p_expire_after timestamptz,
  p_days integer,
  p_source text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.vip_membership_events
    (user_email, event_type, days, occurred_at, expire_before, expire_after, source)
  VALUES (
    p_email,
    CASE WHEN p_expire_before IS NOT NULL AND p_expire_before > now() THEN 'renew' ELSE 'new' END,
    greatest(1, p_days), now(), p_expire_before, p_expire_after, p_source
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_admin_vip_monthly_activity(p_admin_token text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_stats jsonb;
BEGIN
  IF NOT public._blys_monthly_stats_admin(p_admin_token) THEN
    RETURN jsonb_build_object('ok', false, 'msg', '无权限');
  END IF;

  WITH real_events AS (
    SELECT e.*
    FROM public.vip_membership_events e
    JOIN public.profiles p ON lower(p.email) = lower(e.user_email)
    WHERE NOT coalesce(p.is_admin, false)
      AND NOT coalesce(p.is_demo_account, false)
      AND NOT coalesce(p.exclude_from_stats, false)
  ), monthly AS (
    SELECT to_char(date_trunc('month', occurred_at AT TIME ZONE 'Asia/Shanghai'), 'YYYY-MM') AS month_key,
           count(*) FILTER (WHERE event_type = 'new')::integer AS new_count,
           count(*) FILTER (WHERE event_type = 'renew')::integer AS renew_count,
           0::integer AS lapsed_count
    FROM real_events
    WHERE occurred_at >= timestamptz '2026-08-01 00:00:00+08'
    GROUP BY 1
    UNION ALL
    SELECT to_char(date_trunc('month', e.expire_after AT TIME ZONE 'Asia/Shanghai'), 'YYYY-MM') AS month_key,
           0::integer, 0::integer,
           count(DISTINCT lower(e.user_email))::integer AS lapsed_count
    FROM real_events e
    WHERE e.expire_after >= timestamptz '2026-08-01 00:00:00+08'
      AND e.expire_after <= now()
      AND NOT EXISTS (
        SELECT 1 FROM real_events next_event
        WHERE lower(next_event.user_email) = lower(e.user_email)
          AND next_event.occurred_at > e.occurred_at
          AND next_event.occurred_at <= e.expire_after
      )
    GROUP BY 1
  ), monthly_totals AS (
    SELECT month_key,
           sum(new_count)::integer AS new_count,
           sum(renew_count)::integer AS renew_count,
           sum(lapsed_count)::integer AS lapsed_count
    FROM monthly
    GROUP BY month_key
  )
  SELECT coalesce(jsonb_object_agg(month_key, jsonb_build_object(
    'new', new_count,
    'renew', renew_count,
    'lapsed', lapsed_count
  )), '{}'::jsonb)
  INTO v_stats
  FROM monthly_totals;

  RETURN jsonb_build_object('ok', true, 'stats', coalesce(v_stats, '{}'::jsonb));
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_vip(p_admin_token text, p_email text, p_days integer)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_new_expire timestamptz;
  v_old_expire timestamptz;
  v_email text;
BEGIN
  IF length(coalesce(p_admin_token, '')) < 10 THEN
    RETURN json_build_object('ok', false, 'msg', '无权限');
  END IF;

  IF p_days < 0 THEN
    UPDATE public.profiles SET vip_expire = null WHERE lower(email) = lower(p_email);
    RETURN json_build_object('ok', true, 'vip_expire', null);
  END IF;

  SELECT email, vip_expire INTO v_email, v_old_expire
  FROM public.profiles WHERE lower(email) = lower(p_email) FOR UPDATE;
  IF v_email IS NULL THEN RETURN json_build_object('ok', false, 'msg', '用户不存在'); END IF;

  UPDATE public.profiles
  SET vip_started_at = coalesce(vip_started_at, now()),
      vip_expire = now() + (p_days || ' days')::interval
  WHERE lower(email) = lower(p_email)
  RETURNING vip_expire INTO v_new_expire;

  PERFORM public._blys_log_vip_membership_event(v_email, v_old_expire, v_new_expire, p_days, 'admin_set');
  RETURN json_build_object('ok', true, 'vip_expire', v_new_expire);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_extend_vip(p_admin_token text, p_email text, p_days integer default 30)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_new_expire timestamptz;
  v_old_expire timestamptz;
  v_email text;
BEGIN
  IF NOT _blys_is_admin_token(p_admin_token) THEN RETURN json_build_object('ok', false, 'msg', '无权限'); END IF;
  p_days := greatest(1, least(coalesce(p_days, 30), 3660));

  SELECT email, vip_expire INTO v_email, v_old_expire
  FROM public.profiles WHERE lower(email) = lower(p_email) FOR UPDATE;
  IF v_email IS NULL THEN RETURN json_build_object('ok', false, 'msg', '用户不存在'); END IF;

  UPDATE public.profiles
  SET vip_started_at = coalesce(vip_started_at, now()),
      vip_expire = greatest(coalesce(vip_expire, now()), now()) + make_interval(days => p_days)
  WHERE lower(email) = lower(p_email)
  RETURNING vip_expire INTO v_new_expire;

  PERFORM public._blys_log_vip_membership_event(v_email, v_old_expire, v_new_expire, p_days, 'admin_extend');
  RETURN json_build_object('ok', true, 'vip_expire', v_new_expire);
END;
$function$;

CREATE OR REPLACE FUNCTION public.redeem_code(p_token text, p_code text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_user record;
  v_code record;
  v_new_expire timestamptz;
BEGIN
  SELECT email, vip_expire, vip_started_at INTO v_user FROM public.profiles WHERE token = p_token FOR UPDATE;
  IF v_user IS NULL THEN RETURN json_build_object('ok', false, 'msg', '登录已过期'); END IF;

  SELECT * INTO v_code FROM public.member_codes WHERE upper(code) = upper(trim(p_code)) LIMIT 1 FOR UPDATE;
  IF v_code IS NULL THEN RETURN json_build_object('ok', false, 'msg', '激活码不存在或已失效'); END IF;
  IF NOT coalesce(v_code.active, true) THEN RETURN json_build_object('ok', false, 'msg', '激活码已停用'); END IF;
  IF v_code.used_at IS NOT NULL THEN RETURN json_build_object('ok', false, 'msg', '激活码已被使用'); END IF;
  IF v_code.expires_at IS NOT NULL AND v_code.expires_at < now() THEN RETURN json_build_object('ok', false, 'msg', '激活码已过期'); END IF;
  IF v_code.assigned_email IS NOT NULL AND lower(v_code.assigned_email) <> lower(v_user.email) THEN RETURN json_build_object('ok', false, 'msg', '该激活码不属于当前账号'); END IF;

  v_new_expire := greatest(coalesce(v_user.vip_expire, now()), now()) + make_interval(days => v_code.days);
  UPDATE public.profiles SET vip_started_at = coalesce(vip_started_at, now()), vip_expire = v_new_expire WHERE token = p_token;
  UPDATE public.member_codes SET used_by = v_user.email, used_at = now(), active = false WHERE code = v_code.code;
  PERFORM public._blys_log_vip_membership_event(v_user.email, v_user.vip_expire, v_new_expire, v_code.days, 'redeem_code');
  RETURN json_build_object('ok', true, 'vip_expire', v_new_expire, 'days', v_code.days);
END;
$function$;

GRANT EXECUTE ON FUNCTION public.get_admin_vip_monthly_activity(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.admin_list_users(p_admin_token text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE v_list json;
BEGIN
  IF length(coalesce(p_admin_token, '')) < 10 THEN
    RETURN json_build_object('ok', false, 'msg', '无权限');
  END IF;

  SELECT json_agg(row_to_json(t)) INTO v_list
  FROM (
    SELECT p.email, p.nickname, coalesce(p.is_admin, false) AS is_admin, (p.vip_expire > now()) AS is_vip,
           p.vip_started_at, p.vip_expire, p.created_at,
           count(e.id) FILTER (WHERE e.event_type = 'renew')::integer AS vip_renew_count
    FROM public.profiles p
    LEFT JOIN public.vip_membership_events e ON lower(e.user_email) = lower(p.email)
    GROUP BY p.email, p.nickname, p.is_admin, p.vip_started_at, p.vip_expire, p.created_at
    ORDER BY p.created_at DESC
  ) t;

  RETURN json_build_object('ok', true, 'list', coalesce(v_list, '[]'::json));
END;
$function$;

GRANT EXECUTE ON FUNCTION public.admin_list_users(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.admin_stats(p_admin_token text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_users int; v_vip int; v_cmts int;
  v_new_users_today int; v_new_users_yesterday int;
  v_new_vip_today int; v_new_vip_yesterday int;
  v_today_start timestamptz := date_trunc('day', now() AT TIME ZONE 'Asia/Shanghai') AT TIME ZONE 'Asia/Shanghai';
BEGIN
  IF length(coalesce(p_admin_token, '')) < 10 THEN
    RETURN json_build_object('ok', false, 'msg', '无权限');
  END IF;
  SELECT count(*) INTO v_users FROM public.profiles WHERE NOT coalesce(is_demo_account, false) AND NOT coalesce(exclude_from_stats, false);
  SELECT count(*) INTO v_vip FROM public.profiles
   WHERE vip_expire > now() AND NOT coalesce(is_admin, false) AND NOT coalesce(is_demo_account, false) AND NOT coalesce(exclude_from_stats, false);
  SELECT count(*) INTO v_cmts FROM public.comments;
  SELECT count(*) INTO v_new_users_today FROM public.profiles
   WHERE created_at >= v_today_start AND NOT coalesce(is_demo_account, false) AND NOT coalesce(exclude_from_stats, false);
  SELECT count(*) INTO v_new_users_yesterday FROM public.profiles
   WHERE created_at >= v_today_start - interval '1 day' AND created_at < v_today_start
     AND NOT coalesce(is_demo_account, false) AND NOT coalesce(exclude_from_stats, false);
  SELECT count(*) INTO v_new_vip_today
  FROM public.vip_membership_events e JOIN public.profiles p ON lower(p.email) = lower(e.user_email)
   WHERE e.event_type = 'new' AND e.occurred_at >= v_today_start
     AND NOT coalesce(p.is_admin, false) AND NOT coalesce(p.is_demo_account, false) AND NOT coalesce(p.exclude_from_stats, false);
  SELECT count(*) INTO v_new_vip_yesterday
  FROM public.vip_membership_events e JOIN public.profiles p ON lower(p.email) = lower(e.user_email)
   WHERE e.event_type = 'new' AND e.occurred_at >= v_today_start - interval '1 day' AND e.occurred_at < v_today_start
     AND NOT coalesce(p.is_admin, false) AND NOT coalesce(p.is_demo_account, false) AND NOT coalesce(p.exclude_from_stats, false);
  RETURN json_build_object(
    'ok', true, 'users', v_users, 'vip', v_vip, 'comments', v_cmts,
    'new_users_today', v_new_users_today, 'new_users_yesterday', v_new_users_yesterday,
    'new_vip_today', v_new_vip_today, 'new_vip_yesterday', v_new_vip_yesterday
  );
END;
$function$;

GRANT EXECUTE ON FUNCTION public.admin_stats(text) TO anon, authenticated;
NOTIFY pgrst, 'reload schema';
